[repository]
name = "hyprland-plugins"
authors = ["Vaxry"]

[csgo-vulkan-fix]
description = "A plugin to fix incorrect mouse offsets on csgo in Vulkan"
authors = ["Vaxry"]
output = "csgo-vulkan-fix/csgo-vulkan-fix.so"
build = [
    "make -C csgo-vulkan-fix all",
]
